name: Build HWFW_GUI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '15.0'

    - name: Build Debug
      run: msbuild HWFW_GUI.sln /p:Configuration=Debug /p:Platform=Win32

    - name: Build Release
      run: msbuild HWFW_GUI.sln /p:Configuration=Release /p:Platform=Win32

    - name: Build Release_LLVM
      run: msbuild HWFW_GUI.sln /p:Configuration=Release_LLVM /p:Platform=Win32
